#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())
    b = bin(n)
    b = b[2::1]
    b = b.split('0')
    print(max(map(len,b)))
